### ISSUE TITLE
Potential GPL-3 violations in other components

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/compiler-builtins#321]
I'm not sure how to interpret @dvc94ch [comment](https://github.com/rust-lang/compiler-builtins/issues/319#issuecomment-547383921):

> The cabi references the spec, targets do not reference the cortexm targets, rt I think references cortexm rt and the official sdk, e310x references the spec, board support crates reference their schematics

but the intent appears to be for this to hint that all those components also contain GPL-3 violations.

**Comment by dvc94ch** [comment]
An alternative interpretation might be I didn't wake up in the morning and think, let's violate some gpl3 today, but didn't pay particular attention, and wherever that may have occured it's certainly attributed

**Comment by gnzlbg** [comment]
> An alternative interpretation might be I didn't wake up in the morning and think, let's violate some gpl3 today, 

@dvc94ch **This isn't your fault!** (really, it isn't your fault at all, the whole situation about software IP is just super unfortunate). We have a problem that we need to fix, and that requires identifying the GPL-3 code first, and then deciding what to do about it. I pinged you because I was hoping you could help, and you just helped _a lot_ by mentioning that everywhere that happened it was attributed. That will save us a lot of time, so thank you, really.

**Comment by skade** [comment]
No one is currently in violation of GPL, we just cannot accept GPLed code into this repository to make sure _others don't end up being in violation_. Attribution is not the problem, indeed, having added the comment made sure that we catch this.

The problem lies in _shipping_ this code. The problem is also certainly not with @dvc94ch, we accepted the code although this was glaringly obvious.

The only thing I asked for in the other issue is the confirmation that this is the only instance of something ported over from GCC, to avoid doing the whole dance again for another instance. If this is the case, we'll just replace it and move on.

**Comment by dvc94ch** [comment]
I don't think there are any other glaringly obvious instances. I mostly looked at the llvm backend, and the sifive sdk is MIT and Apache licensed.

**Comment by gnzlbg** [comment]
> No one is currently in violation of GPL, we just cannot accept GPLed code into this repository to make sure others don't end up being in violation. 

@skade this repo contains code copy & pasted from the GCC compiler under the GPL-3 license, that code is silently embedded on Rust programs for certain targets, and users might be distributing those binaries without providing all their source code, which is something that the GPL-3 license requires. 

So... are we sure that nobody is shipping any code anywhere for this target without providing all their source code? (maybe the involved targets aren't stable, or don't work, or something?).

---

Closing this because all code with attribution to GNU is already covered in the other issue.
