### ISSUE TITLE
`u128_divide_sparc` get build into rust stdlib for x86_64-pc-windows-msvc target

### ISSUE THREAD

**Issue by klensy** [rust-lang/compiler-builtins#422]
Checked exported symbols for `std-[hash].dll` for current stable and nightly and found `_ZN17compiler_builtins3int19specialized_div_rem8delegate17u128_divide_sparc17hd4dfbbe4547e607fE` inside, i guess #393 is source of this.

I guess sparc related functions shouldn't get build into other os stdlib.

**Comment by Amanieu** [comment]
cc @AaronKutch

**Comment by AaronKutch** [comment]
There are a number of hidden function specializations (another example is `usize_leading_zeros_riscv`) which are public so that they can get tested by the test suite which is in a separate crate. The CI does not have SPARC or RISCV which is why these are always enabled. I think I once wanted to make a feature flag for making these functions public, that would only be enabled by the testcrate. I can't remember why I never did it, I will open a PR and try doing it again.
